AllCops:
  Exclude:
    - no_patch.gemspec

Documentation:
  Enabled: false

LineLength:
  Enabled: true
  Max: 140

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes
